### ISSUE TITLE
Make zgen work with prezto

### ISSUE THREAD

**Issue by svenstaro** [tarjoilija/zgen#11]
prezto is a pretty popular framework alternative to omz. It should be pretty easy to add support for it.

**Comment by tarjoilija** [comment]
There's a pull request #27 but I can't verify it right now.

**Comment by m42e** [comment]
@svenstaro You may try #40.

**Comment by breerly** [comment]
curious what's up with this... I'm using prezto and I'd like to install autosuggestions w zgen since prezto doesn't have that vendored like it's other "pmodule's"

**Comment by jedahan** [comment]
this can be closed, yes?
