### ISSUE TITLE
Why does zgen need a special directive for completions whereas antigen needs only one?

### ISSUE THREAD

**Issue by svenstaro** [tarjoilija/zgen#13]
As the heading says, I wonder why we need to care and distinguish between `completion` and `load` whereas in antigen there is just `bundle`. Wouldn't it be more straight forward for people switching if the same syntax rules applied with slightly different naming?

Some plugins provide both completions and functionality. What to do about them?

**Comment by tarjoilija** [comment]
I like the idea of combining ```completion``` and ```load```.

TODO
- move the logic part from ```completion``` to ```load```
- make ```load``` output some useful information like what gets sourced and appended to fpath
