### ISSUE TITLE
Remove zgen and revert

### ISSUE THREAD

**Issue by ThSGM** [tarjoilija/zgen#131]
I'm going to ask a really dumb question, but it might be that the answer is complex enough and useful to others: suppose we want to remove zgen (installed via the usual git clone to .zgen) and revert back to a default zsh and oh-my-zsh configuration. 

What is the best way to do that? I assume that we shouldn't just delete the .zgen directory and revert to a backup of .zshrc but if you could provide the breakdown of steps, that would be immensely helpful.

**Comment by jandamm** [comment]
Hi @ThSGM, I'd be interested why you want to switch back to `ohmyzsh`. I'm maintaining a fork of zgen with a some additions and other improvements: [zgenom](https://github.com/jandamm/zgenom). 

To answer your question:
I'd create a backup of your current zshrc and restore the ohmyzsh zshrc.
Then check if everything is still working. Maybe you have to clone ohmyzsh again. Removing `~/.zgen` isn't necessary to switch back to ohmyzsh but it cleans up your computer so I'd remove it when you're sure your ohmyzsh config is working.

**Comment by ThSGM** [comment]
Hi @jandamm 

It's a pretty simple answer that won't really be relevant: I'm a beginner and learning about customisation, zsh, etc. For beginners it's easy to jump in too quickly, especially when you're trying to read random posts on the internet. I read that we should use zgen to optimise for speed. 

However, because I didn't understand the basics enough, I realised I need to learn better about ohmyzsh and the more popularised routes. I would be open to returning to zgen and zegnom once I get a better understanding of the limitations of the more popular packages.

**Comment by jandamm** [comment]
@ThSGM I see your point but wouldn't say that's really the case.

If you actually want to learn about zsh you should use a plugin manager (zgen, zgenom, zinit ...).
I'd only recommend to use ohmyzsh if you want to use zsh and don't want to learn how to use/configure zsh.

ohmyzsh is by far the most popular zsh framework. But you end up just using "someone elses config" and just add a array of plugins you want to include (with the configuration done by the community).

Using a plugin manager gives you the possibility to use ohmyzsh alongside with other plugins (the ones not included in ohmyzsh)*.
When you're ready to take over control you can remove ohmyzsh plugins and configure them yourself. (You can find most plugins here: [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins))

This is actually the route I went. I started with ohmyzsh, then used zgen and bit after bit removed ohmyzsh.

\* ohmyzsh does support this as well but it requires you managing everything

**Comment by ThSGM** [comment]
Thanks for the advice. I think this can now be closed.
