### ISSUE TITLE
Function, zgen-load, does not load files with extension ".plugin.zsh".

### ISSUE THREAD

**Issue by rbose85** [tarjoilija/zgen#22]
I would like to include the `autojump` plugin from [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/autojump). The `autojump` plugin folder contains a single file, `autojump.plugin.zsh`. Unfortunately, however, when I list `autojump` in my `~/.zshrc` file the `autojump.plugin.zsh` script does not get invoked. As a result I cannot use the `autojump` utility at all. :(

`~/.zshrc` is as follows:

```bash
#!/usr/bin/env zsh

# load zgen
source ~/Code/opensrc/zgen/zgen.zsh

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # plugins
    zgen oh-my-zsh plugins/autojump

    # theme
    zgen oh-my-zsh themes/ys

    # save all to init script
    zgen save
fi
```

I'm pretty sure issue is to do with the logic of the `zgen-load()` function, within the `zgen.zsh` file. The below diff was enough for me to fix the problem in my setup. 

![screenshot 2015-03-10 15 06 09](https://cloud.githubusercontent.com/assets/2758507/6577633/4e4a0fa0-c737-11e4-8eab-c841712d39f0.png)

However, I am not yet offering a pull request as I am uncertain as to the ramifications of this change ... If, as is the case for the `brew` plugin, an oh-my-zsh plugin folder contains both a `brew.plugin.zsh` file and the a `_brew` file, does this change prevent the `_brew` completions file from being added to `fpath` if the `brew.plugin.zsh` file is run?

For completeness, I am working with a clean install for `zgen` and my ZSH version:

```bash
$ zsh --version
zsh 5.0.7 (x86_64-apple-darwin14.0.0)
```

**Comment by tarjoilija** [comment]
Hello,

Unfortunately I have not been able to reproduce your issue.

Did you remember to run ```zgen update``` or ```zgen reset``` after adding the plugin to ```.zshrc```? This is crucial because zgen won't otherwise rewrite the init script.

**Comment by rbose85** [comment]
Hah!  I'm an idiot. Many thanks. Please close this ticket.

**Comment by tarjoilija** [comment]
It's my bad. The readme file lacks a lot information and has to be updated.
