### ISSUE TITLE
Zgen won't load bullet-train-oh-my-zsh-theme

### ISSUE THREAD

**Issue by johnhamelink** [tarjoilija/zgen#24]
In the readme for bullet-train-oh-my-zsh-theme, it states that you can install using zgen by running:

    zgen load caiogondim/bullet-train-oh-my-zsh-theme

I can see that in my .zgen, the repository has been cloned, however when a new terminal is opened, this message appears:

    /home/john/.zgen/robbyrussell/oh-my-zsh-master/oh-my-zsh.sh:source:96: no such file or directory: /home/john/.zgen/robbyrussell/oh-my-zsh-master/themes/bullet-train.zsh-theme

This makes me think that the script which is being generated is just looking for oh-my-zsh somewhere in the string url and attributing bullet-train-oh-my-zsh-theme as an oh-my-zsh theme incorrectly.

**Comment by tarjoilija** [comment]
Hello,

Unfortunately I could not reproduce your problem on my platform. Can you give me some information about your setup like zsh version and OS?

I found out that bullet-train-oh-my-zsh-theme has a strange format that is not supported by zgen. Please try this instead:
```zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train```

**Comment by johnhamelink** [comment]
I'm using zsh 5.0.7 on arch linux (using termite as my terminal).

I managed to get it to load with your command, but it looks like this:

![screenshot](http://i.imgur.com/befxrSf.png)

**Comment by faceleg** [comment]
I had to add:

```
ZSH_THEME="bullet-train" 
```

To my `.zshrc` for this theme to work.

**Comment by tarjoilija** [comment]
I managed to reproduce this issue by removing ```zgen oh-my-zsh``` line from my config. The theme requires oh-my-zsh and you should load it too.

    zgen oh-my-zsh
    zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train
    zgen save
