### ISSUE TITLE
zgen breaks if CLOBBER is unset

### ISSUE THREAD

**Issue by jouberthenk** [tarjoilija/zgen#25]
I keep `setopt noclobber` in my zshrc

This breaks the save function because `zgen-reset` removes `${ZGEN_INIT}` if it exists, then tries to write to it with `>>` which causes an error.

You probably want `>!` for the first line, which removes the need for the `zgen-reset` call as a side effect.

**Comment by tarjoilija** [comment]
Thank you!

**Comment by jouberthenk** [comment]
Thanks!
