### ISSUE TITLE
zgen selfupdate not working

### ISSUE THREAD

**Issue by spiffin** [tarjoilija/zgen#30]
Hello. On my installation (Mac Yosemite, home dir) there seems to be an issue with ZGEN_SOURCE so that running zgen selfupdate results in:

`zgen is not running from a git repository, so it is not possible to selfupdate`

.. even though it is running from a git repo (cd-ing to that dir and running git pull works fine).

Do you have a clue what the issue might be?

Thanks.

**Comment by tarjoilija** [comment]
I think the problem lies on line 2:
```local ZGEN_SOURCE="$(cd "$(dirname "${0}")" && pwd -P)"```

There's something that's not Mac compliant. There has been some discussion about this in #23

Unfortunately my time and resources are so limited right now that I can't develop zgen for next few weeks.

**Comment by spiffin** [comment]
Thanks. Yes, it's definitely line 2. I'm brushing up on my shell scripting - if I figure out a fix, I'll let you know.

**Comment by spazzwig** [comment]
I reproduced this (from OS X Yosemite $HOME)... and then when poking at zgen.zsh realized it went away after I had sourced my env again.
@spiffin have you tried from a freshly sourced shell?

**Comment by spiffin** [comment]
Thanks @spazzwig - sourcing zgen.zsh fixes it.
