### ISSUE TITLE
zgen themes aren't working properly.

### ISSUE THREAD

**Issue by Nixpower** [tarjoilija/zgen#35]
Hello, I'm attempting to edit the theme for zgen, and in my `.zshrc` file I have:

    zgen oh-my-zsh themes/agnoster

But it still returns to the "arrow" theme, even after closing and reopening the session.

Thanks, 
nixpower

**Comment by tarjoilija** [comment]
Run ```zgen reset``` and restart the shell

**Comment by Nixpower** [comment]
Thank you, this has fixed the issue for me.
