### ISSUE TITLE
Lots of `zsh -i` are spawned, CPU pegged to 100%.

### ISSUE THREAD

**Issue by mkaito** [tarjoilija/zgen#36]
Upon doing a `zgen reset` today, and restarting the shell, zgen hangs and doesn't seem to make no progress (no ouput after 15 minutes). Checking `ps`, there are 195 instances of `zsh -i`. `pkill zsh` kills them and gives me a prompt, but the same happens every time I open a shell now.

**Comment by mattbowen** [comment]
Same here --- walking backward through the commits, up through 1f3953028018255072640433787a9ceca714035c everything is fine, but then once I move up to d46ccf9053aa9394b5707a512e07a3df7e74be2f ("Improve performance") I end up with the pegged processor and many, many zshes.

**Comment by mkaito** [comment]
Stopped happening when I removed the `tarruda/zsh-autosuggestions` plugin. Maybe I should go bug him instead.

**Comment by tarjoilija** [comment]
```-zgen-path-contains()``` didn't support symbolic links which forced zgen to load every file in that directory.

Let me know if it works now.

**Comment by kilogram** [comment]
I had the same problem, and it is solved for me after a `zgen selfupdate` and a `zgen update`. Thank you!

**Comment by forivall** [comment]
My bad sorry. I broke the build :imp:
