### ISSUE TITLE
Local repositories are not loaded if they are submodules

### ISSUE THREAD

**Issue by jojoelfe** [tarjoilija/zgen#37]
Trying to load a local repository fails, if it is a submodule of another repository.

This is probably because zgen-get-clone-url() checks for the presence of a directory named .git, which in the case of submodules is a file.

**Comment by tarjoilija** [comment]
This used to work but apparently something broke it.. addd587151767833a21e349c2b89de37fff87ecd does it work for you now?

**Comment by jojoelfe** [comment]
Yes, that fixed it. Thanks!
