### ISSUE TITLE
prezto syntax-highlighting not working

### ISSUE THREAD

**Issue by dan-silva** [tarjoilija/zgen#48]
When using the following command, the generated code in init.zsh is wrong:

```
  zgen prezto 'syntax-highlighting' highlighters \
    'main' \
    'brackets' \
    'pattern' \
    'root'

```

becomes...

```
zstyle ':prezto:module:syntax-highlighting' highlighters 'main brackets pattern root'
```

PS: It looks like it was working on the @m42e fork before the #40 merge, not sure if there was any change on the merged code.

**Comment by m42e** [comment]
If I try your configuration, I only get the following:
```
zstyle ':prezto:module:syntax-highlighting' highlighters 'main'
```
but you are right, It won't work as expected (But I'm not sure it worked anytime before)

**Comment by dan-silva** [comment]
It's working now. Thank you!

**Comment by m42e** [comment]
You're welcome
