### ISSUE TITLE
Weird behaviour with tmux

### ISSUE THREAD

**Issue by felixSchl** [tarjoilija/zgen#53]
So, tmux crashes - or at least involuntarily exists on behalf of me - whenever I `source zgen/zgen.zsh`. I have removed everything else from my `.zshrc`, so it's definitely related to calling `source zgen/zgen.zsh`.

More symptoms: tmux will open fine at first, but when I add a split, the split just dies right after. Sometimes, it will succeed creating the split, but creating another one may tear the whole thing down again. Tmux would then exit and print `[exited]`. The behaviour that surprises me most is that, say it managed to create 3 splits, closing one of them would bring down the entire tmux run.

My zgen install is up-to-date, I am on OSX (iTerm2) and zsh 5.0.2 (from brew).

**Comment by felixSchl** [comment]
Alright, it seems related to my `.tmux.conf` as well. It all works fine on a completely empty `.tmux.conf`. Adding `set-option -g default-command "reattach-to-user-namespace -l zsh"` to it, causes the behaviour. So something about the combination of `reattach-to-user-namespace` and `zgen`?

**Comment by tarjoilija** [comment]
Hey,

I've merged a bunch of pull requests lately. Do you still have this issue?

**Comment by felixSchl** [comment]
Yes, the problem remains to exist with the most basic of `.zshrc`s:

```
source "${HOME}/.zgen/zgen.zsh"
if ! zgen saved; then
  # load oh my zsh
  zgen oh-my-zsh
  zgen save
fi
```

(copy and paste from project README)

I can see that without specifiying the syntax-highlighting plugin, zgen just enables it, and it [appears to be the main culprit](b4b4r07/zplug#35).

**Comment by tarjoilija** [comment]
`zsh-syntax-highlighting` should not be enabled by default with that `.zshrc`. It may come from an old init script. Make sure you have refreshed the `.zgen/init.zsh` file by either removing it or running `zgen reset` and then restart the shell.

I've understood that `reattach-to-user-namespace` is a OSX namespace wrapper that does some questionable stuff on the shell. Unfortunately I don't have the resources to reproduce this issue.

**Comment by felixSchl** [comment]
Alright, removing `~/.zgen/init.zsh` does work with the above `.zshrc`. But this one seems to fail:

```
source "${HOME}/.zgen/zgen.zsh"
if ! zgen saved; then
  # load oh my zsh
  zgen oh-my-zsh
  zgen oh-my-zsh plugins/vi-mode # <--- also load vi-mode
  zgen load zsh-users/zsh-syntax-highlighting
  zgen save
fi
```

The same thing happens for zplug. Hm, maybe it's vi-mode then... but vi-mode works fine on it's own, also. It's something about the combination.

**Comment by felixSchl** [comment]
Yeah, it happens even with this `.zshrc`:

```
source ~/.zplug/repos/robbyrussell/oh-my-zsh/plugins/vi-mode/vi-mode.plugin.zsh
source ~/.zplug/repos/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

I am happy to close this, I guess it's not relevant to zgen in particular. Your call.

**Comment by tarjoilija** [comment]
Good luck with the issue hunting.
