### ISSUE TITLE
vim mode plugin

### ISSUE THREAD

**Issue by DanCardin** [tarjoilija/zgen#57]
Whenever I try to add this https://github.com/sharat87/zsh-vim-mode to loaded pluings, I get unusably slow prompt loading speed (like just pressing enter a few times). In my zshrc it looks like so
```bash
zgen loadall <<EOPLUGINS
    sharat87/zsh-vim-mode
EOPLUGINS
```
however, I can copy the plugin's whole contents directly into my zshrc and it works fine.

**Comment by m42e** [comment]
Well I tried it in OSX and it works as fast as before. can you provide details? Maybe you should share the .zgen/init.zsh content here.

**Comment by DanCardin** [comment]
Im running the latest zgen/init.zsh from here, but I thought I had narrowed it down to that the other day. Its actually the combination of that and loading `zgen oh-my-zsh` like

```bash
zgen oh-my-zsh

zgen loadall <<EOPLUGINS
    sharat87/zsh-vim-mode
EOPLUGINS
```

**Comment by DanCardin** [comment]
I guess its caused by the `zle reset-prompt`, I'm unsure why this makes any difference if its in the imported plugin or manually inside my zshrc.

Its weird its slow for me regardless of where its is inside tmux, and otherwise its only slow when imported through zgen. But either way, I can just replace `reset-prompt` with `redisplay` apparently, so this can probably be closed.
