### ISSUE TITLE
How does this compare to antigen?

### ISSUE THREAD

**Issue by svenstaro** [tarjoilija/zgen#6]
It might be useful to write up a small motivation to explain to users why they might want to use zgen instead of antigen. I, for one, do not currently understand the difference and why I might want to use zgen.

**Comment by tconroy** [comment]
Since this issue is from 2014, I'm curious if there are any more recent comparisons between Antigen and zgen? Is it still safe to assume zgen is considerably faster than Antigen or is that no longer the case?
