### ISSUE TITLE
how to let zgen enable the following line in zpreztorc?

### ISSUE THREAD

**Issue by githubfun** [tarjoilija/zgen#62]
https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zpreztorc
line 22
    # zstyle ':prezto:load' zfunction 'zargs' 'zmv'

I tried to uncomment the line in my
~/.zgen/sorin-ionescu/prezto-master/runcoms/zpreztorc

and did zgen reset. 

But I still can't use zmv. Thank!

**Comment by tarjoilija** [comment]
You can't modify plugins directly inside ```~/.zgen``` directory. You have to do it somewhere else.
