### ISSUE TITLE
Sourcing zgen binds Alt-/

### ISSUE THREAD

**Issue by psprint** [tarjoilija/zgen#63]
The following lines in zgen.zsh re-bind Alt-/

``` zsh
ZGEN_AUTOLOAD_COMPINIT=${ZGEN_AUTOLOAD_COMPINIT:-true}
if $ZGEN_AUTOLOAD_COMPINIT; then
    autoload -U compinit
    compinit -d "${ZGEN_DIR}/zcompdump"
fi
```

Specifically it's "compinit" that does that. Either compinit needs to be stopped from doing this, or the bindkey should be saved and then restored, after doing compinit

**Comment by tarjoilija** [comment]
Hey,

I approved the PR that changed compinit handling. Please let me know if this problem persits.
