### ISSUE TITLE
zgen load only supports github

### ISSUE THREAD

**Issue by ressu** [tarjoilija/zgen#64]
I have one of my repos on bitbucket that I wish to load with zgen. Currently the only way to accomplish this is to clone the repository manually and using zgen load with the path option.

It would be very useful if we could define git repository paths to checkout arbitrary locations. Github is just one location which can host ZSH scripts.

**Comment by tarjoilija** [comment]
Poor documentation!

I have now updated the readme file to show different ways to pass repository to zgen load 30e212e

It may be a good idea to add shortcuts to other git hosting services too.. We'll see if there's enough demand for that.

**Comment by ressu** [comment]
Nice, that actually does allow you to use other repositories. Too bad bitbucket offers the url git@bitbucket.org:user/repo.git for private repos. It doesn't fit the supported usage patterns.

It's not a big deal to rewrite that into a git:// url, but since it's directly supported by git, it would be nice if zgen allowed it as well.

**Comment by tarjoilija** [comment]
I'll see if I can manage to craft a pattern for that

**Comment by ressu** [comment]
That should do the trick. Thanks.
