### ISSUE TITLE
Using OMZ plugins without loading all of OMZ

### ISSUE THREAD

**Issue by tofagerl** [tarjoilija/zgen#69]
Is this possible? There are a few plugins I can't live without, but when I load all of OMZ I get all these extra aliases and stuff I neither need nor want. 
Obviously I could unalias all of those, but there seems like there should be a better solution.

**Comment by m42e** [comment]
Doesn't just `zgen oh-my-zsh plugins/git` work?

**Comment by tofagerl** [comment]
No, I get all these compdef command not found errors.
Hold on, I'll edit this post with the exact error...

**Comment by m42e** [comment]
Well, there is something missing, the default setup of OMZ does for you.

Add the following before calling zgen
```zsh
autoload -Uz compinit
compinit
```
And that should propably do the trick.
Please let me know if this worked for you

**Comment by tofagerl** [comment]
Yep, that was the missing piece :)

Thanks!

**Comment by tofagerl** [comment]
Yep, it was a powerline setting that OMZ probably overwrote by default. Fixed it by copying the default shell settings file, putting it in ~/.config/powerline/themes/shell/default.conf and removing key "powerline.segments.shell.mode".
