### ISSUE TITLE
Update Prezto repo

### ISSUE THREAD

**Issue by beloso** [tarjoilija/zgen#88]
There is a new repo for Prezto which is more updated

https://github.com/zsh-users/prezto

Could Zgen update it's prezto repo to the new one? Or is there a way to change the repo?

**Comment by m42e** [comment]
Just set:
    ZGEN_PREZTO_REPO=zsh-users

**Comment by beloso** [comment]
I've tried that, but it isn't loading prezto modules from zsh-users repo

**Comment by beloso** [comment]
i've fixed it, it was a problem with an outdated symbolic link

**Comment by Cottser** [comment]
https://github.com/sorin-ionescu/prezto is active again, so IMO this can be closed.

**Comment by beloso** [comment]
@m42e had fixed the issue for me anyways :)
